micronaut:
  application:
    name: kuokko-api

  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - ".*"

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /docs/**

jackson:
  serializationInclusion: NON_NULL
