version: '2'

services:
  kuokko-front:
    build:
      dockerfile: docker/front.docker
      context: ..

    ports:
      - 4444:80
   
  kuokko-db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: kuokko_dev
      POSTGRES_USER: kuokko
      POSTGRES_PASSWORD: kuokko

    ports:
      - 5432:5432

  kuokko-api:
    build:
      dockerfile: docker/recipes.docker
      context: ..

    depends_on:
      - kuokko-db

    links:
      - kuokko-db

    ports:
      - 3333:8080
      
